--- #YAML:1.0
name:                WWW-Patent-Page
version:             0.106.0
abstract:            get patent documents
license:             ~
author:              
    - Wanda B. Anon <Wanda_B_Anon@yahoo.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Archive::Zip:                  0
    base:                          0
    Carp:                          0
    Data::Dumper:                  0
    diagnostics:                   0
    English:                       0
    File::Spec:                    0
    File::Temp:                    0.17
    HTML::Form:                    0
    HTML::HeadParser:              0
    HTML::TokeParser:              0
    HTTP::Headers:                 0
    HTTP::Request::Common:         0
    HTTP::Response:                0
    IO::Scalar:                    0
    LWP::UserAgent:                0
    PDF::API2:                     0.53
    strict:                        0
    subs:                          0
    Test::More:                    0
    URI:                           0
    vars:                          0
    version:                       0
    warnings:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
