---
name: WWW-Patent-Page
version: 0.105.3
author:
  - 'Wanda B. Anon <Wanda_B_Anon@yahoo.com>'
abstract: "get patent documents\r\nfrom WWW source (e.g. JP->Eng translations in HTML from JPO, complete US applications and grants from \r\n(USPTO), pdf documents from the esp@cenet at the European Patent Office (ESPACE_EP), and\r\nplace into a WWW::Patent::Page::Response object)"
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Archive::Zip: 0
  Carp: 0
  Data::Dumper: 0
  English: 0
  File::Temp: 0.17
  HTML::Form: 0
  HTML::HeadParser: 0
  HTML::TokeParser: 0
  HTTP::Headers: 0
  HTTP::Request: 0
  HTTP::Request::Common: 0
  HTTP::Response: 0
  IO::Scalar: 0
  LWP::UserAgent: 2.003
  PDF::API2: 0.52
  Test::More: 0
  URI: 0
  base: 0
  diagnostics: 0
  strict: 0
  subs: 0
  version: 0
  warnings: 0
provides:
  WWW::Patent::Page:
    file: lib/WWW/Patent/Page.pm
    version: 0.105.3
  WWW::Patent::Page::ESPACE_EP:
    file: lib/WWW/Patent/Page/ESPACE_EP.pm
    version: 0.21
  WWW::Patent::Page::JPO_IPDI:
    file: lib/WWW/Patent/Page/JPO_IPDI.pm
    version: 0.01
  WWW::Patent::Page::MICROPATENT:
    file: lib/WWW/Patent/Page/MICROPATENT.pm
    version: 0.06
  WWW::Patent::Page::USPTO:
    file: lib/WWW/Patent/Page/USPTO.pm
    version: 0.28
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
