# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Patent-Page
version:      0.101.0
version_from: lib/WWW/Patent/Page.pm
installdirs:  site
requires:
    English:                       0
    File::Temp:                    0.16
    HTML::HeadParser:              0
    HTML::TokeParser:              0
    HTTP::Request:                 0
    HTTP::Response:                0
    LWP::UserAgent:                2.003
    PDF::API2:                     2.00
    Test::More:                    0
    version:                       0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
